name: Deploy to VPS

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            # Navigate to project directory
            cd /opt/faces

            # Clean untracked files that might conflict
            echo "Cleaning untracked files..."
            git clean -fd

            # Pull latest code
            echo "Pulling latest changes..."
            git pull origin master

            # Update nginx config if changed
            echo "Syncing nginx configuration..."
            sed 's/{{DOMAIN}}/${{ secrets.DOMAIN }}/g' nginx-vps.conf > /tmp/faces-nginx.conf
            sudo cp /tmp/faces-nginx.conf /etc/nginx/sites-available/faces
            sudo nginx -t && sudo systemctl reload nginx

            # Build and deploy containers
            echo "Building and deploying containers..."
            docker compose down
            docker compose build --no-cache
            docker compose up -d

            # Wait for health checks
            echo "Waiting for services to be healthy..."
            sleep 15

            # Check container status
            docker compose ps

            # Clean up old images
            echo "Cleaning up unused Docker resources..."
            docker image prune -af

            echo "✅ Deployment complete!"

      - name: Notify deployment status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Deployment successful"
          else
            echo "❌ Deployment failed"
          fi
